<?php

namespace DoctrineORMModule\Proxy\__CG__\Guest\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Guest extends \Guest\Entity\Guest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'id', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'name', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'surname', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'gender', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'email', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'connection', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'partner', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'inviteMorning', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'inviteEvening', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'viewedAt', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'attendMorning', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'attendEvening', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'repliedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'id', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'name', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'surname', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'gender', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'email', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'connection', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'partner', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'inviteMorning', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'inviteEvening', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'viewedAt', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'attendMorning', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'attendEvening', '' . "\0" . 'Guest\\Entity\\Guest' . "\0" . 'repliedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Guest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function populate(array $values = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($values));

        return parent::populate($values);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function toJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', array());

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function fullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fullName', array());

        return parent::fullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', array());

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerName', array());

        return parent::getPartnerName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', array());

        return parent::getPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function getInviteMorning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInviteMorning', array());

        return parent::getInviteMorning();
    }

    /**
     * {@inheritDoc}
     */
    public function getInviteEvening()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInviteEvening', array());

        return parent::getInviteEvening();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendMorning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendMorning', array());

        return parent::getAttendMorning();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendEvening()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendEvening', array());

        return parent::getAttendEvening();
    }

    /**
     * {@inheritDoc}
     */
    public function getViewedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewedAt', array());

        return parent::getViewedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepliedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepliedAt', array());

        return parent::getRepliedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function getConnection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnection', array());

        return parent::getConnection();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function setConnection($connection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnection', array($connection));

        return parent::setConnection($connection);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', array($surname));

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner(\Guest\Entity\Guest $partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', array($partner));

        return parent::setPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function setViewedAt($viewedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewedAt', array($viewedAt));

        return parent::setViewedAt($viewedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setInviteMorning($inviteMorning)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInviteMorning', array($inviteMorning));

        return parent::setInviteMorning($inviteMorning);
    }

    /**
     * {@inheritDoc}
     */
    public function setInviteEvening($inviteEvening)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInviteEvening', array($inviteEvening));

        return parent::setInviteEvening($inviteEvening);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendMorning($attendMorning)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendMorning', array($attendMorning));

        return parent::setAttendMorning($attendMorning);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendEvening($attendEvening)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendEvening', array($attendEvening));

        return parent::setAttendEvening($attendEvening);
    }

    /**
     * {@inheritDoc}
     */
    public function setRepliedAt($repliedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepliedAt', array($repliedAt));

        return parent::setRepliedAt($repliedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
