<div class="center-page" ng-app="troue">
    <header style="float:right;">
        <a href="/admin_hidden/guest-list-csv">Download Guest List</a> |
        <a href="/admin_hidden/both-list-csv">Download Both List</a> |
        <a href="/admin_hidden/morning-list-csv">Download Morning List</a> |
        <a href="/admin_hidden/evening-list-csv">Download Evening List</a> |
        <a href="/admin_hidden/morning-guests-csv">Download Morning Guests</a> |
        <a href="/admin_hidden/evening-guests-csv">Download Evening Guests</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#/guests">Guests</a> |
        <a href="#/morning">Morning</a> |
        <a href="#/evening">Evening</a>
    </header>
    <div class="" ng-view></div>
</div>
