<div class="center-page" ng-app="troue">
    <header style="float:right;">
        <a href="/admin_hidden/guest-list-csv">Download Guest List</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#/guests">Guests</a> |
        <a href="#/morning">Morning</a> |
        <a href="#/evening">Evening</a>
    </header>
    <div class="" ng-view></div>
</div>
