<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Marnus & Nora-ann trou!</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="/css/app.css"/>

        <script src="/lib/angular/angular.js"></script>
        <script src="/lib/angular/angular-route.js"></script>
        <script src="/lib/angular/angular-resource.js"></script>
        <script src="/lib/angular/angular-sanitize.js"></script>
        <script src="/lib/bootstrap-ui/position/position.js"></script>
        <script src="/lib/bootstrap-ui/datepicker/datepicker.js"></script>
        <script src="/js/admin/app.js"></script>
        <script src="/js/admin/filters.js"></script>
        <script src="/js/admin/services.js"></script>
        <script src="/js/admin/directives.js"></script>
        <script src="/js/admin/controllers.js"></script>
    </head>
    <body>
        <?php echo $this->content; ?>
        
        <script src="/lib/jquery-1.11.1.min.js"></script>
        <script src="/js/img.js"></script>
        <script src="/js/frames.js"></script>
        <script src="/js/animator.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
